### ISSUE TITLE
How to depict Fig.3 in your paper?

### ISSUE THREAD

**Issue by youngwanLEE** [ruinmessi/RFBNet#11]
Hi,
I'm really impressed by your good work.

As shown Fig3, I want to depict the effective receptive field like you. 

Could you share the method?

**Comment by ruinmessi** [comment]
@youngwanLEE  I use the same gradient bp method in "Understanding the effective receptive field
in deep convolutional neural networks".

**Comment by youngwanLEE** [comment]
@ruinmessi Could you share the program?

**Comment by ruinmessi** [comment]
@youngwanLEE That is a messy and tiny scripts. What I do is that forwarding one picture, then define a zero grad tensor except the center. Using "output.backward(Zero_grad)" to bp, and the effective rf data is "input.grad.data.cpu()", where input and output are the Variables of your module or network.
