### ISSUE TITLE
How to reproduce the COCO result

### ISSUE THREAD

**Issue by qijiezhao** [ruinmessi/RFBNet#12]
Hi, I feel excited about your amazing work and I am trying to reproduce the training process. May I ask about the training arguments of COCO dataset? In detail, --batch_size, --max_epoch and so on.

Thanks for your reply!

**Comment by ruinmessi** [comment]
Using default arguments is enough to reproduce the results. And for COCO, at least 130 training epoches is needed. If you  have sufficient GPU resources, enlarge the batch size and lr would get better performance.

**Comment by qijiezhao** [comment]
Seems that a training and testing process will cost whole 4 and 1 day respectively if we want to reproduce the COCO result. (Our hardware is based on Titan 1080ti)
