### ISSUE TITLE
In config.py, coco-512 settings are different from those of voc-512.

### ISSUE THREAD

**Issue by zhanghaoinf** [ruinmessi/RFBNet#14]
Hi, ruinmessi,

Thank you for sharing your impressive work, but I have some questions while reading the codes.
When I am using RFB_NET_E_512, I found the anchor-box size of Coco-512 and VOC-512 (min size, max size) differs from each other. Is there any special reasons ? I expected the anchor boxes to be fixed for the same network.   
Thanks & Regards

**Comment by ruinmessi** [comment]
@zhanghaoinf  Since COCO dataset has more small instances than VOC, the anchor-box size differs. You could also refer to the original paper of SSD for more details,
