### ISSUE TITLE
what is the difference between 'RFB_Net_E_vgg.py' and   'RFB_Net_vgg.py'? 

### ISSUE THREAD

**Issue by liuqinying** [ruinmessi/RFBNet#20]
Hello,thanks for your code.But I am confused by the  file 'RFB_Net_E_vgg.py' and   'RFB_Net_vgg.py'.I've seen there are some differences in these two files, but I don't understand what  the different purposes of the two of them are. Can you tell me when should I use the former and when the latter?

**Comment by ruinmessi** [comment]
@liuqinying 'RFB_Net_E' takes two efficient updates: (1) to up-sample the conv7_fc feature maps and concat it with the conv4_3 before applying the RFB module, sharing a similar strategy as in FPN; and (2) to add a branch with a 7x7 kernel in all RFB layers. It is more accurate than 'RFB_Net_vgg' while the computational cost marginally ascends.
