### ISSUE TITLE
The structure of BasicRFB is not same with Fig.4.(a) in your paper

### ISSUE THREAD

**Issue by arlensung** [ruinmessi/RFBNet#23]
Hello, thanks for your code releasing.

There is a branch of 1×1 conv tailed by 3×3 conv rate=1 in Fig.4.(a) in your paper(arXiv:1107.07767v3),which is not shown in class BasicRFB of models/RFB_Net_vgg.py. 
There are other two branch(self.branch0 and self.branch1 in class BasicRFB) and a shortcut connection in your code. So which choice is more helpful in performance?

**Comment by ruinmessi** [comment]
@arlensung Thank you for your kindly commenting. It was a mistake that I had overlooked for a long time!! The current results are obtained by this two branch structure, and I will update the results with the same structure as in the paper soon.

**Comment by ruinmessi** [comment]
@arlensung  Hi, I have fixed the error above, and now the correct RFBNet300 achieved 80.7% mAP in VOC2007. You can check the latest commit for details of both [RFB structure](https://github.com/ruinmessi/RFBNet/blob/master/models/RFB_Net_vgg.py#L29-L67) and new [model weight](https://drive.google.com/open?id=1apPyT3IkNwKhwuYyp432IJrTd0QHGbIN). The COCO model is still under training, but a tiny improvement could also be expected.
