### ISSUE TITLE
map of RFB_mobile trained on VOC is 71.16% 

### ISSUE THREAD

**Issue by xtanitfy** [ruinmessi/RFBNet#28]

**Comment by xtanitfy** [comment]
Is that correct？The map is a little lower than caffe-ssd_mobilenet.

**Comment by ruinmessi** [comment]
@xtanitfy I have not trained RFB_mobile on VOC yet, but the prior config in this repository is set for COCO, so I suggest you modify the parameters.

**Comment by Damon2019** [comment]
@xtanitfy hi,could you tell me how to train RFB_mobile on VOC? thanks very much
