### ISSUE TITLE
Do you have RetinaNet + Resnet101

### ISSUE THREAD

**Issue by isalirezag** [ruinmessi/RFBNet#29]
Can this model be used together with resnet101 and is so, Do you guys the results of  RetinaNet + Resnet101? 
Is it possible to share please?

**Comment by ruinmessi** [comment]
@isalirezag This model can be used with any backbone. But we do not have the results of Resnet101 because of the limit GPU resources.

**Comment by Damon2019** [comment]
> Can this model be used together with resnet101 and is so, Do you guys the results of RetinaNet + Resnet101?
> Is it possible to share please?

@isalirezag  hi, You have achieved RetinaNet or Resnet101

**Comment by Damon2019** [comment]
> Can this model be used together with resnet101 and is so, Do you guys the results of RetinaNet + Resnet101?
> Is it possible to share please?

@isalirezag  hi, are you achieved RetinaNet or Resnet101?
