### ISSUE TITLE
High overhead GPU to CPU 

### ISSUE THREAD

**Issue by evroni** [ruinmessi/RFBNet#3]
The conversion of boxes (cuda float tensors) which are returned from the detector forward to cpu float tensors has extremely high overhead.  (I ignored the conversion to numpy array,takes about a microsecond)

boxes = boxes.cpu().numpy()

It takes approximately 22 milliseconds on a 512 input size (detection time is approximately 9 milliseconds)

**Comment by ruinmessi** [comment]
@evroni Thanks a lot! I only thought that time-consuming was mainly from NMS,  and ignored that conversion process. But I have no idea how to eliminate that consuming.
Maybe I could write a cuda version nms, but the evaluation code is still need numpy boxes input. Any suggestions?

**Comment by evroni** [comment]
@ruinmessi Running the nms on the GPU is a good idea ,you can use:
https://github.com/ruotianluo/pytorch-faster-rcnn/tree/master/lib/nms.

BTW,how did measure the RFBNet  times you published? the same as in ur test_RFB.py script?

**Comment by ruinmessi** [comment]
@evroni Thanks! I only count the inference time + NMS time in my script, and the published results are just average.

**Comment by evroni** [comment]
@ruinmessi if u measure the time in ur script test_RFB.py, begin from the for loop till nms_time u shell get around three times compare to the times u currently measuring.At the beginning, it seems that the GPU to CPU memcpy caused this overhead,but even after I use a gpu nms implementation the entire measured time stays the same (the nms on the GPU is a bit less than 1/2.) 

I decided to run the script with CUDA_LAUNCH_BLOCKING=1,taking into account the asynchronized computations of the CUDA kernels,and then only the forward pass (out = self.net(x) ) takes around 35ms.

**Comment by ruinmessi** [comment]
@evroni  CUDA_LAUNCH_BLOCKING=1 would definitely slow down the forward pass. And although you use a gpu nms, the evaluation of dataset still need a numpy array. So I think the GPU to CPU memcpy is still the reason for this overhead if you use the evaluation code.

**Comment by ruinmessi** [comment]
@evroni  I add a 'time' [branch](https://github.com/ruinmessi/RFBNet/tree/time) to use gpu nms and measure every part of the test_RFB.py. In my experiments, excluding the img load time, the main time consume seems come from the nms for loop. Very weird ..........
