### ISSUE TITLE
About some train details

### ISSUE THREAD

**Issue by dlyldxwl** [ruinmessi/RFBNet#30]

**Comment by dlyldxwl** [comment]
thanks for sharing the code!
I want to reimplement the network in other framework,, but i have some confuse.
when you train rfbnet in VOC, which pretrain model you used? vgg-reduce or ssd or direct train? and when finetune, did you freeze some layers weight?
Thank you!

**Comment by ruinmessi** [comment]
@dlyldxwl Hi, thanks for your attention.
I use vgg-reduce weight for the pretrain model on both VOC and COCO, and I didn't freeze any layers during training.

**Comment by dlyldxwl** [comment]
Thank for you reply~
could you please give me  your qq number ?  I want to ask some questions. my qq is844518133
thanks~

**Comment by ruinmessi** [comment]
@dlyldxwl Well, you could send me an email (liusongtao@buaa.edu.cn).
