### ISSUE TITLE
About the FPS (RFB and SSD)

### ISSUE THREAD

**Issue by hokuto-HIRANO** [ruinmessi/RFBNet#31]
In the paper, SSD has larger FPS than RFB.
However, RFB has larger FPS than SSD in this repository.

Why are these different?

**Comment by ruinmessi** [comment]
@hokuto-HIRANO The FPS of SSD in this repository is just referred from the original SSD paper. But in the paper, we re-implement the SSD with pytorch for fair comparison.

**Comment by hokuto-HIRANO** [comment]
Thank you! I understood.
