### ISSUE TITLE
How to use the txt format label files

### ISSUE THREAD

**Issue by wgqlovewzr** [ruinmessi/RFBNet#32]
The code is based on xml format label file, but I want to use txt format label file....., I have tried to modified voc0712.py, but I failed (crying), Please help me...I really need your help
Thank you so much for your kindness!!

**Comment by ruinmessi** [comment]
@wgqlovewzr You could just modify the AnnotationTransform class in voc0712 to read txt file and convert the label to the same form as [[xmin, ymin, xmax, ymax, label_ind], ... ].
