### ISSUE TITLE
the difference of the backbone between vgg and mobilenet

### ISSUE THREAD

**Issue by hectorgui** [ruinmessi/RFBNet#33]
Hi, Songtao Liu:
    Glad to read your paper, one question has no relationship with the code.
    In your paper, it seems that the vgg is much powerful than mobilenet, For example,  VGGNet300 + RFB  in coco test could get MAP30.3, while the SSD 300 MobileNet+RFB only get MAP20.7
    my conclusion is right or not ?

**Comment by ruinmessi** [comment]
@hectorgui Yes, you are right.

**Comment by hectorgui** [comment]
One another question, the speed also improved, but I could get the reason. It seems the speed should become slow due to many dilated convolutions has been introduce
