### ISSUE TITLE
The final loss

### ISSUE THREAD

**Issue by litingsjj** [ruinmessi/RFBNet#37]
Good work! Can you tell me the final loss when you finish training. And how should I judge it? Thanks a lot!

**Comment by ruinmessi** [comment]
@litingsjj  The final loss is about 1.5~2.0 for VOC and 2.0~3.0 for COCO.

**Comment by feixiangdekaka** [comment]
> @litingsjj The final loss is about 1.5 - 2.0 for VOC and 2.0 - 3.0 for COCO.
Have you try focal_loss replace mutibox_loss ?
