### ISSUE TITLE
regarding min_sizes and max_size in config file

### ISSUE THREAD

**Issue by isalirezag** [ruinmessi/RFBNet#38]
can you please suggest how should i define the min_sizes and max_sizes for a costume dataset?

**Comment by ruinmessi** [comment]
@isalirezag It mainly depends on your input size and the object size distribution of your dataset. I only use the default setting from original SSD, e.g., [0.1,0.2,0.37,0.54,0.7,0.88] of input size for VOC300. For your own dataset, I suggest you  use k-means like in YOLOv2, or just follow the original SSD.
