### ISSUE TITLE
More details about the parameters in Table 3 of your paper

### ISSUE THREAD

**Issue by ZhengMengbin** [ruinmessi/RFBNet#40]
Thanks for your brilliant work. I want to know how to calculate the parameters in Table 3?
Such as RFB's parameters 34.5M in Table 3, I do not get the result, so can you give me some details about it?
![screenshot from 2018-10-04 21-27-58](https://user-images.githubusercontent.com/26650043/46477137-81601f80-c81c-11e8-9195-f69e0ea766b7.png)
I calculate the parameters as follows:
(1)VGG16(base net)
conv1_1: weights  64(output numbers)x3(input numbers)x3x3(kernel size)=1728; bias  64(output numbers)
conv1_2: weights  64x64x3x3=36864; bias  64
......
fc7: weights  1024x1024x1x1=1048576; bias  1024
total: 12220096(weights)+6272(bias)=12226368=12.226368M
(2)RFB(fc7)
branch0: (1x1conv)weights 256x1024x1x1=262144, bn(batch norm) 256(output numbers)x2=512
               (3x3conv)weights 256x256x3x3=589824, bn(batch norm) 256(output numbers)x2=512
branch1:(1x1conv)weights 128x1024x1x1=131072, bn(batch norm) 128(output numbers)x2=256
               (3x3conv)weights 256x128x3x3=294912, bn(batch norm) 256(output numbers)x2=512
               (3x3conv)weights 256x256x3x3=589824, bn(batch norm) 256(output numbers)x2=512
branch2:(1x1conv)weights 128x1024x1x1=131072, bn(batch norm) 128(output numbers)x2=256
               (3x3conv)weights 192x128x3x3=221184, bn(batch norm) 192(output numbers)x2=384
               (3x3conv)weights 256x192x3x3=442368, bn(batch norm) 256(output numbers)x2=512
               (3x3conv)weights 256x256x3x3=589824, bn(batch norm) 256(output numbers)x2=512
ConvLinear: weights 1024x768x1x1=786432, bn(batch norm) 1024(output numbers)x2=2048
shortcut: weights 1024x1024x1x1=1048576, bn(batch norm) 1024(output numbers)x2=2048
total: 5087232(weights)+8064(bn)=5095396=5.095396M
(3)RFB(stride 2 or conv8)
total: 4169728(weights)+6016(bn)=4175744=4.175744M
(4)RFB(stride 2 or conv9)
total: 1042432(weights)+3008(bn)=1045440=1.04544M
(5)conv10_1: weights 128x256=32768; bn 128x2=256
conv10_2: weights 256x128x3x3=294912; bn 256x2=512
conv11_1: weights 128x256=32768; bn 128x2=256
conv11_2: weights 256x128x3x3=294912; bn 256x2=512
total: 655360(weights)+1536(bn)=656896=0.656896M
(6)multi_box
conv4_3: conf weights (21x6)x512x3x3=580608; conf bias 21x6=126
                loc weights (4x6)x512x3x3=110592; loc bias 4x6=24
fc7:conf weights (21x6)x1024x3x3=1161216; conf bias 21x6=126
      loc weights (4x6)x1024x3x3=221184; loc bias 4x6=24
conv8:conf weights (21x6)x512x3x3=580608; conf bias 21x6=126
           loc weights (4x6)x512x3x3=110592; loc bias 4x6=24
conv9:conf weights (21x6)x256x3x3=290304; conf bias 21x6=126
           loc weights (4x6)x256x3x3=55296; loc bias 4x6=24
conv10_2:conf weights (21x4)x256x3x3=193536; conf bias 21x4=84
                loc weights (4x4)x256x3x3=36864; loc bias 4x4=16
conv11_2:conf weights (21x4)x256x3x3=193536; conf bias 21x4=84
                loc weights (4x4)x256x3x3=36864; loc bias 4x4=16
total: 3571200(weights)+800(bn)=3572000=3.572M
above all, the total parametes are: 12.226368+5.095396+4.175744+1.04544+0.656896+3.572=26.771844M < 34.5M
Do you think my calculation is correct? Why do I calculate so many fewer parameters?
Any comments will be appreciated.
Thanks.

**Comment by ruinmessi** [comment]
@ZhengMengbin Thank you for your attention. I actually didn't calculate the parameters by hand. What I do is just use weights.numel() to get the number of parameters of each layer and sum up, just a few lines of code.

**Comment by ZhengMengbin** [comment]
Thank you very much for answering my question. I will try the numel() function to calculate automatically.
Because the VOC 2007 mAp corresponding to 34.5M in Table 3 is 80.1, compared with Table 2, I think it is  without RFB_s.
![image](https://user-images.githubusercontent.com/26650043/46514688-f0c42680-c891-11e8-8b8a-b68dcf3d31c0.png)
