### ISSUE TITLE
More details about Fig.3 in your paper?

### ISSUE THREAD

**Issue by ZhengMengbin** [ruinmessi/RFBNet#42]
Hi, thanks for your brilliant work.
I want to know how to draw Fig.3 in your paper, I had tried the method you said in #11. But I can not get that beautiful picture.
There are four questions I want to ask:
Q1: The effective receptive field drawn in Fig.3 is which module's input gradient map (RFB module after conv4_3, fc7, conv8 or conv9)
Q2: You said in #11 that the input is an image, what is the number of channels in this image (as conv4_3's RFB has 512 channels; fc7's RFB has 1024 channels...)?
Q3: The author in "Understanding the effective receptive field in deep convolutional neural networks" only describes the case where all convolutional layers are one channel. There is no description of multi-channel conditions, such as the RFB module followed by the fc7 layer, the input of this module has 1024 channels (feature map’s size is 19x19), the output also has 1024 channels, then the gradient of the central pixel on which channel is set to 1.0, that is, \frac{\partial l}{\partial y_{0,0}}(LaTeX code) in the paper.
![screenshot from 2018-10-06 16-59-46](https://user-images.githubusercontent.com/26650043/46569541-44656b80-c989-11e8-9c3e-100b9f561a58.png)
Q4: The input of the module is multi-channel, that is, the input gradient map is also multi-channel. Then, is the final effective receptive field image selected one of the channels, or is an average value obtained on all channels? Or other operations?

My code for drawing the effective receptive field image is as follows (where the input is a randomly generated 1x1024x19x19 size feature map, the module uses RFB after fc7, the output gradient map takes Zero_grad[0][512][9][9] = 1.0, and the rest are 0): [temp.txt](https://github.com/ruinmessi/RFBNet/files/2452875/temp.txt) (as the uploaded code is messy, I put it in temp.txt and cut the graph as follows)
![screenshot from 2018-10-06 17-12-55](https://user-images.githubusercontent.com/26650043/46569697-1719bd00-c98b-11e8-8712-ca60b30c9bfa.png)
![screenshot from 2018-10-06 17-14-52](https://user-images.githubusercontent.com/26650043/46569711-6102a300-c98b-11e8-90cf-ebe995e0f73c.png)

But the image I got is as follows, and it is very different from Fig.3, so I don't know if it is caused by the details reflected in the above four questions.
![screenshot from 2018-10-06 16-50-59](https://user-images.githubusercontent.com/26650043/46569507-e2a50180-c988-11e8-8bb1-37b1ec09b8ed.png)

**Comment by ruinmessi** [comment]
@ZhengMengbin Thanks for your attention. I have input an image to the detector, not the random tensor. And I use the sum of the abs(grad) among channels.  The issues in the this repo are more about the reproduction or bugs of the code. If you have more questions, please send me an email liusongtao@buaa.edu.cn.
