### ISSUE TITLE
How can i get MS COCO 'train2014(or2017)_gt_roidb.pkl'file in cache folder?

### ISSUE THREAD

**Issue by seongkyun** [ruinmessi/RFBNet#45]
I'm trying to train this code on my pc with your instructions.
But there is a problem that generating `~_gt_roidb.pkl` process.
I've read dataset instructions but nothing explained about generating MS COCO cache folder and `~_gt_roidb.pkl` file, even can not find the method on [https://github.com/rbgirshick/py-faster-rcnn/blob/77b773655505599b94fd8f3f9928dbf1a9a776c7/data/README.md](url) .
Is there any way to get that file to train this model?

**Comment by seongkyun** [comment]
It was just directory problem.
Just making `~/data/COCO/cache` directory can solve this problem.

**Comment by lc17721825** [comment]
is there anyone who got the train(minval)_gt_roidb.pkl? How to get that? Thanks in advance

**Comment by seongkyun** [comment]
@GuoGuoYao and @lc17721825 , Just make the folder named `cache` in the directory of MS COCO dataset. As for my case, my MS COCO directory is existing in the home directory (`~/data/COCO`) and I've made `cache` folder in that MSCOCO directory. You guys don't have to find out or download `_gt_roidb.pkl` file. Just making `cache` folder can solve this problem.

**Comment by lc17721825** [comment]
Well, my bad, sorry. Thanks a lot!!!
