### ISSUE TITLE
Reproducibility of RFB speed

### ISSUE THREAD

**Issue by underfitting** [ruinmessi/RFBNet#46]
Hi,

I think you should add `torch.cuda.synchronize()` inside timer(e.g. after `net(x) `), because CUDA is asynchronous.
By adding this, I got ~0.12s/forward.

**Comment by ruinmessi** [comment]
The current inference time measurement followed as faster rcnn. Moreover, each forward only process a single image at test, so we do not need synchronize to depress the power of CUDA.
