### ISSUE TITLE
Can I use my dataset to train this code ?

### ISSUE THREAD

**Issue by yuyijie1995** [ruinmessi/RFBNet#47]
I used my dataset to make a VOClike dataset and changed the VOC classes like 
VOC_CLASSES = ( '__background__', # always index 0
    'Car', 'Cyclist', 'Pedestrain')
but the error below happened 
Traceback (most recent call last):
  File "/home/jsu/下载/pycharm-community-2018.2/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/jsu/下载/pycharm-community-2018.2/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/jsu/下载/pycharm-community-2018.2/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/jsu/下载/pycharm-community-2018.2/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/jsu/yuyijie/RFBNet/train_RFB.py", line 257, in <module>
    train()
  File "/home/jsu/yuyijie/RFBNet/train_RFB.py", line 208, in train
    images, targets = next(batch_iterator)
  File "/home/jsu/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/jsu/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
KeyError: 'Traceback (most recent call last):\n  File "/home/jsu/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/jsu/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/jsu/yuyijie/RFBNet/data/voc0712.py", line 185, in __getitem__\n    target = self.target_transform(target)\n  File "/home/jsu/yuyijie/RFBNet/data/voc0712.py", line 136, in __call__\n    label_idx = self.class_to_ind[name]\nKeyError: \'car\'\n'
Could not find thread pid_14959_id_139789338658968
Available: ['pid_14959_id_139790992515760', 'pid_14959_id_139790992516208', 'pid_14959_id_139790992472160', 'pid_14959_id_139789339129280', 'pid_14959_id_139789452204296']
Could not find thread pid_14959_id_139789339129560
Available: ['pid_14959_id_139790992515760', 'pid_14959_id_139790992516208', 'pid_14959_id_139790992472160', 'pid_14959_id_139789339129280', 'pid_14959_id_139789452204296']
Could not find thread pid_14959_id_139790992329136
Available: ['pid_14959_id_139790992515760', 'pid_14959_id_139790992516208', 'pid_14959_id_139790992472160', 'pid_14959_id_139789339129280', 'pid_14959_id_139789452204296']
Could not find thread pid_14959_id_139789339129840
Available: ['pid_14959_id_139790992515760', 'pid_14959_id_139790992516208', 'pid_14959_id_139790992472160', 'pid_14959_id_139789339129280', 'pid_14959_id_139789452204296']
Could not find thread pid_14959_id_139789339129000
Available: ['pid_14959_id_139790992515760', 'pid_14959_id_139790992516208', 'pid_14959_id_139790992472160', 'pid_14959_id_139789339129280', 'pid_14959_id_139789452204296']
Could not find thread pid_14959_id_139789441732792
Available: ['pid_14959_id_139790992515760', 'pid_14959_id_139790992516208', 'pid_14959_id_139790992472160', 'pid_14959_id_139789339129280', 'pid_14

**Comment by BestSongEver** [comment]
Could you please tell me how did you fix the problem?
I am trying to train the code on a dataset with only 2 classes
Thanks

**Comment by BestSongEver** [comment]
@yuyijie1995 
Could you please tell me how did you fix the problem? 
I am trying to train the code on a dataset with only 2 classes
Thanks

**Comment by BestSongEver** [comment]
@yuyijie1995 

Could you please tell me how did you fix the problem? 
I am trying to train the code on a dataset with only 2 classes
Thanks

**Comment by dodogoffy** [comment]
@yuyijie1995 
Could you please tell me how did you fix the problem?
I am trying to train the code on a dataset with only 4 classes
Thanks
