### ISSUE TITLE
RFB-max pooling in paper

### ISSUE THREAD

**Issue by zhangjiamin** [ruinmessi/RFBNet#48]
Hi, ruinmessi:
    Thank your Great codes, I have some questions:
    In paper 4.2 Ablation Study mention that By simply replacing the last convolution layer with the 
           RFB-max pooling, we can see that the result is impoved to 79.1%。
    What the RFB-max pooling refer to ? The RFB(stride 2) ? 
    Which is the last convolution layer ?
    Here the learning rate strategy is same as code? Warmup  then use 4e-3, then decay by 0.1?
    If it is convenient， Could I have your WeChat ID?
   Thank you!

**Comment by ruinmessi** [comment]
@zhangjiamin  RFB-max pooling uses dilated max pooling layer instead of dilated conv in each RFB-block. Other strategy is the same. If you have more questions about the paper, please send me an email. (liusongtao@buaa.edu.cn).
