### ISSUE TITLE
TEST error

### ISSUE THREAD

**Issue by yuyijie1995** [ruinmessi/RFBNet#49]
When I finished the training step and use the trained weight to test ,the mismatch error below happened .
I used my dataset to make the VOClike dataset and trained the net .Where should I changed when I use the weight to test ?
RuntimeError: Error(s) in loading state_dict for RFBNet:
	size mismatch for conf.0.weight: copying a param of torch.Size([24, 512, 3, 3]) from checkpoint, where the shape is torch.Size([126, 512, 3, 3]) in current model.
	size mismatch for conf.0.bias: copying a param of torch.Size([24]) from checkpoint, where the shape is torch.Size([126]) in current model.

**Comment by ruinmessi** [comment]
@yuyijie1995 Make sure the model defined in your test script is the same as your training, e.g., num_class, input size.

**Comment by yuyijie1995** [comment]
It seems like  base net weights are missing ,and I only found the num_class to change ,I don't know how to modify the testscript's input size
Missing key(s) in state_dict: "base.0.0.weight", "base.0.1.weight", "base.0.1.bias", "base.0.1.running_mean", "base.0.1.running_var", "base.1.0.weight", "base.1.1.weight", "base.1.1.bias", "base.1.1.running_mean", "base.1.1.running_var", "base.1.3.weight", "base.1.4.weight", "base.1.4.bias", "base.1.4.running_mean", "base.1.4.running_var", "base.2.0.weight", "base.2.1.weight", "base.2.1.bias", "base.2.1.running_mean", "base.2.1.running_var", "base.2.3.weight", "base.2.4.weight", "base.2.4.bias", "base.2.4.running_mean", "base.2.4.running_var", "base.3.0.weight", "base.3.1.weight", "base.3.1.bias", "base.3.1.running_mean", "base.3.1.running_var", "base.3.3.weight", "base.3.4.weight", "base.3.4.bias", "base.3.4.running_mean", "base.3.4.running_var", "base.4.0.weight", "base.4.1.weight", "base.4.1.bias", "base.4.1.running_mean", "base.4.1.running_var", "base.4.3.weight", "base.4.4.weight", "base.4.4.bias", "base.4.4.running_mean", "base.4.4.running_var", "base.5.0.weight", "base.5.1.weight", "base.5.1.bias", "base.5.1.running_mean", "base.5.1.running_var", "base.5.3.weight", "base.5.4.weight", "base.5.4.bias", "base.5.4.running_mean", "base.5.4.running_var", "base.6.0.weight", "base.6.1.weight", "base.6.1.bias", "base.6.1.running_mean", "base.6.1.running_var", "base.6.3.weight", "base.6.4.weight", "base.6.4.bias", "base.6.4.running_mean", "base.6.4.running_var", "base.7.0.weight", "base.7.1.weight", "base.7.1.bias", "base.7.1.running_mean", "base.7.1.running_var", "base.7.3.weight", "base.7.4.weight", "base.7.4.bias", "base.7.4.running_mean", "base.7.4.running_var", "base.8.0.weight", "base.8.1.weight", "base.8.1.bias", "base.8.1.running_mean", "base.8.1.running_var", "base.8.3.weight", "base.8.4.weight", "base.8.4.bias", "base.8.4.running_mean", "base.8.4.running_var", "base.9.0.weight", "base.9.1.weight", "base.9.1.bias", "base.9.1.running_mean", "base.9.1.running_var", "base.9.3.weight", "base.9.4.weight", "base.9.4.bias", "base.9.4.running_mean", "base.9.4.running_var", "base.10.0.weight", "base.10.1.weight", "base.10.1.bias", "base.10.1.running_mean", "base.10.1.running_var", "base.10.3.weight", "base.10.4.weight", "base.10.4.bias", "base.10.4.running_mean", "base.10.4.running_var", "base.11.0.weight", "base.11.1.weight", "base.11.1.bias", "base.11.1.running_mean", "base.11.1.running_var", "base.11.3.weight", "base.11.4.weight", "base.11.4.bias", "base.11.4.running_mean", "base.11.4.running_var", "base.12.0.weight", "base.12.1.weight", "base.12.1.bias", "base.12.1.running_mean", "base.12.1.running_var", "base.12.3.weight", "base.12.4.weight", "base.12.4.bias", "base.12.4.running_mean", "base.12.4.running_var", "base.13.0.weight", "base.13.1.weight", "base.13.1.bias", "base.13.1.running_mean", "base.13.1.running_var", "base.13.3.weight", "base.13.4.weight", "base.13.4.bias", "base.13.4.running_mean", "base.13.4.running_var", "extras.0.branch1.3.conv.weight", "extras.0.branch1.3.bn.weight", "extras.0.branch1.3.bn.bias", "extras.0.branch1.3.bn.running_mean", "extras.0.branch1.3.bn.running_var", "extras.1.conv.weight", "extras.1.bn.weight", "extras.1.bn.bias", "extras.1.bn.running_mean", "extras.1.bn.running_var", "extras.2.conv.weight", "extras.2.bn.weight", "extras.2.bn.bias", "extras.2.bn.running_mean", "extras.2.bn.running_var". 
	Unexpected key(s) in state_dict: "base.14.weight", "base.14.bias", "base.17.weight", "base.17.bias", "base.19.weight", "base.19.bias", "base.21.weight", "base.21.bias", "base.24.weight", "base.24.bias", "base.26.weight", "base.26.bias", "base.28.weight", "base.28.bias", "base.31.weight", "base.31.bias", "base.33.weight", "base.33.bias", "base.0.weight", "base.0.bias", "base.2.weight", "base.2.bias", "base.5.weight", "base.5.bias", "base.7.weight", "base.7.bias", "base.10.weight", "base.10.bias", "base.12.weight", "base.12.bias", "Norm.shortcut.conv.weight", "Norm.shortcut.bn.weight", "Norm.shortcut.bn.bias", "Norm.shortcut.bn.running_mean", "Norm.shortcut.bn.running_var", "Norm.shortcut.bn.num_batches_tracked", "extras.0.branch0.0.conv.weight", "extras.0.branch0.0.bn.weight", "extras.0.branch0.0.bn.bias", "extras.0.branch0.0.bn.running_mean", "extras.0.branch0.0.bn.running_var", "extras.0.branch0.0.bn.num_batches_tracked", "extras.0.branch0.1.conv.weight", "extras.0.branch0.1.bn.weight", "extras.0.branch0.1.bn.bias", "extras.0.branch0.1.bn.running_mean", "extras.0.branch0.1.bn.running_var", "extras.0.branch0.1.bn.num_batches_tracked", "extras.1.branch0.0.conv.weight", "extras.1.branch0.0.bn.weight", "extras.1.branch0.0.bn.bias", "extras.1.branch0.0.bn.running_mean", "extras.1.branch0.0.bn.running_var", "extras.1.branch0.0.bn.num_batches_tracked", "extras.1.branch0.1.conv.weight", "extras.1.branch0.1.bn.weight", "extras.1.branch0.1.bn.bias", "extras.1.branch0.1.bn.running_mean", "extras.1.branch0.1.bn.running_var", "extras.1.branch0.1.bn.num_batches_tracked", "extras.1.branch1.0.conv.weight", "extras.1.branch1.0.bn.weight", "extras.1.branch1.0.bn.bias", "extras.1.branch1.0.bn.running_mean", "extras.1.branch1.0.bn.running_var", "extras.1.branch1.0.bn.num_batches_tracked", "extras.1.branch1.1.conv.weight", "extras.1.branch1.1.bn.weight", "extras.1.branch1.1.bn.bias", "extras.1.branch1.1.bn.running_mean", "extras.1.branch1.1.bn.running_var", "extras.1.branch1.1.bn.num_batches_tracked", "extras.1.branch1.2.conv.weight", "extras.1.branch1.2.bn.weight", "extras.1.branch1.2.bn.bias", "extras.1.branch1.2.bn.running_mean", "extras.1.branch1.2.bn.running_var", "extras.1.branch1.2.bn.num_batches_tracked", "extras.1.branch2.0.conv.weight", "extras.1.branch2.0.bn.weight", "extras.1.branch2.0.bn.bias", "extras.1.branch2.0.bn.running_mean", "extras.1.branch2.0.bn.running_var", "extras.1.branch2.0.bn.num_batches_tracked", "extras.1.branch2.1.conv.weight", "extras.1.branch2.1.bn.weight", "extras.1.branch2.1.bn.bias", "extras.1.branch2.1.bn.running_mean", "extras.1.branch2.1.bn.running_var", "extras.1.branch2.1.bn.num_batches_tracked", "extras.1.branch2.2.conv.weight", "extras.1.branch2.2.bn.weight", "extras.1.branch2.2.bn.bias", "extras.1.branch2.2.bn.running_mean", "extras.1.branch2.2.bn.running_var", "extras.1.branch2.2.bn.num_batches_tracked", "extras.1.branch2.3.conv.weight", "extras.1.branch2.3.bn.weight", "extras.1.branch2.3.bn.bias", "extras.1.branch2.3.bn.running_mean", "extras.1.branch2.3.bn.running_var", "extras.1.branch2.3.bn.num_batches_tracked", "extras.1.ConvLinear.conv.weight", "extras.1.ConvLinear.bn.weight", "extras.1.ConvLinear.bn.bias", "extras.1.ConvLinear.bn.running_mean", "extras.1.ConvLinear.bn.running_var", "extras.1.ConvLinear.bn.num_batches_tracked", "extras.1.shortcut.conv.weight", "extras.1.shortcut.bn.weight", "extras.1.shortcut.bn.bias", "extras.1.shortcut.bn.running_mean", "extras.1.shortcut.bn.running_var", "extras.1.shortcut.bn.num_batches_tracked", "extras.2.branch0.0.conv.weight", "extras.2.branch0.0.bn.weight", "extras.2.branch0.0.bn.bias", "extras.2.branch0.0.bn.running_mean", "extras.2.branch0.0.bn.running_var", "extras.2.branch0.0.bn.num_batches_tracked", "extras.2.branch0.1.conv.weight", "extras.2.branch0.1.bn.weight", "extras.2.branch0.1.bn.bias", "extras.2.branch0.1.bn.running_mean", "extras.2.branch0.1.bn.running_var", "extras.2.branch0.1.bn.num_batches_tracked", "extras.2.branch1.0.conv.weight", "extras.2.branch1.0.bn.weight", "extras.2.branch1.0.bn.bias", "extras.2.branch1.0.bn.running_mean", "extras.2.branch1.0.bn.running_var", "extras.2.branch1.0.bn.num_batches_tracked", "extras.2.branch1.1.conv.weight", "extras.2.branch1.1.bn.weight", "extras.2.branch1.1.bn.bias", "extras.2.branch1.1.bn.running_mean", "extras.2.branch1.1.bn.running_var", "extras.2.branch1.1.bn.num_batches_tracked", "extras.2.branch1.2.conv.weight", "extras.2.branch1.2.bn.weight", "extras.2.branch1.2.bn.bias", "extras.2.branch1.2.bn.running_mean", "extras.2.branch1.2.bn.running_var", "extras.2.branch1.2.bn.num_batches_tracked", "extras.2.branch2.0.conv.weight", "extras.2.branch2.0.bn.weight", "extras.2.branch2.0.bn.bias", "extras.2.branch2.0.bn.running_mean", "extras.2.branch2.0.bn.running_var", "extras.2.branch2.0.bn.num_batches_tracked", "extras.2.branch2.1.conv.weight", "extras.2.branch2.1.bn.weight", "extras.2.branch2.1.bn.bias", "extras.2.branch2.1.bn.running_mean", "extras.2.branch2.1.bn.running_var", "extras.2.branch2.1.bn.num_batches_tracked", "extras.2.branch2.2.conv.weight", "extras.2.branch2.2.bn.weight", "extras.2.branch2.2.bn.bias", "extras.2.branch2.2.bn.running_mean", "extras.2.branch2.2.bn.running_var", "extras.2.branch2.2.bn.num_batches_tracked", "extras.2.branch2.3.conv.weight", "extras.2.branch2.3.bn.weight", "extras.2.branch2.3.bn.bias", "extras.2.branch2.3.bn.running_mean", "extras.2.branch2.3.bn.running_var", "extras.2.branch2.3.bn.num_batches_tracked", "extras.2.ConvLinear.conv.weight", "extras.2.ConvLinear.bn.weight", "extras.2.ConvLinear.bn.bias", "extras.2.ConvLinear.bn.running_mean", "extras.2.ConvLinear.bn.running_var", "extras.2.ConvLinear.bn.num_batches_tracked", "extras.2.shortcut.conv.weight", "extras.2.shortcut.bn.weight", "extras.2.shortcut.bn.bias", "extras.2.shortcut.bn.running_mean", "extras.2.shortcut.bn.running_var", "extras.2.shortcut.bn.num_batches_tracked". 
	size mismatch for Norm.branch0.1.conv.weight: copying a param of torch.Size([128, 1, 3, 3]) from checkpoint, where the shape is torch.Size([128,128,3,3])

**Comment by yuyijie1995** [comment]
@ruinmessi

**Comment by Damon2019** [comment]
@yuyijie1995  you should modify --basenet
