### ISSUE TITLE
VOC dataset mAP with my trained-model is 10% lower than RFB300_80_5.pth

### ISSUE THREAD

**Issue by zufall1985** [ruinmessi/RFBNet#5]
hello, 

I just follow your guide step by step and then trained a new VOC model (RFB-300-vgg16). I turned it down when epoches went to 130, so finally I used model with RFB_vgg_VOC_epoches_130.pth in test_RFB.py but only get mAP 70%...
could you help me how can I train RFB model with so good results as yours?
thanks a lot

**Comment by ruinmessi** [comment]
@zufall1985 You should follow my original schedule in train_RFB.py. For VOC, a recommend schedule is 240 epoches, and the lr will decreased by 10 factor at 150 and 200 epoch. so 130 epoch version is not fully converged.
