### ISSUE TITLE
A problem about img channel

### ISSUE THREAD

**Issue by Excalibur0214** [ruinmessi/RFBNet#51]
Hello, first thanks to your amazing open source algorithm.
Maybe it's a minor problem, but I will be appreciated if you have time to answer.
In your data/data_augment.py file, you use cv2 to read img file. As we all know, cv2 reads images in BGR order, but you subtract mean value (104, 117, 123), which is RGB order, as you write in annotation.
A few days ago, I tried to use (123, 117, 104) instead and got a little improve in both precision and recall, and I'm not sure it is because the order of mean value. Would you please help me with this problem?
Thanks again for your great algorithm.

**Comment by ZhengMengbin** [comment]
@Excalibur0214 What mAP did you get?

**Comment by Excalibur0214** [comment]
Thanks to your reply.
I trained the model on my own dataset and got 1 percent better than rgb order mean. When I subtract [104, 117, 123]，onison my own testset, the recall is 81.8%. When I subtract [123, 117, 104], the recall is 82.7%.
I used to try using resnet/fpn instead of vgg, cleaning dataset and other tricks, but they are all uselesshelps or even harmful. So I'm not sure whether the order of mean value helps.




    
    
        
            
                
                    
                        
                    
                    
                        
                            576849023
                            
                            
                                
                                    邮箱：576849023@qq.com
                                
                        
                    
                
            
        
    
Signature is customized by Netease Mail Master


On 10/22/2018 19:59, ZhengMengbin wrote: @Excalibur0214 What mAP did you get?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ruinmessi/RFBNet","title":"ruinmessi/RFBNet","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ruinmessi/RFBNet"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ZhengMengbin in #51: @Excalibur0214 What mAP did you get?"}],"action":{"name":"View Issue","url":"https://github.com/ruinmessi/RFBNet/issues/51#issuecomment-431814079"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ruinmessi/RFBNet/issues/51#issuecomment-431814079",
"url": "https://github.com/ruinmessi/RFBNet/issues/51#issuecomment-431814079",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [ruinmessi/RFBNet] A problem about img channel (#51)",
"sections": [
{
"text": "",
"activityTitle": "**ZhengMengbin**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@ZhengMengbin",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"ruinmessi/RFBNet\",\n\"issueId\": 51,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"ruinmessi/RFBNet\",\n\"issueId\": 51\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/ruinmessi/RFBNet/issues/51#issuecomment-431814079"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 395246939\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by ruinmessi** [comment]
@Excalibur0214  I think (104, 117, 123) is already the BGR order.

**Comment by xi-mao** [comment]
@Excalibur0214  did you think the VGG16 model is trained with image channels order BGR?

**Comment by xi-mao** [comment]
@ruinmessi  can I ask you that your VGG model is trained with input image channel RGB or BGR?

**Comment by Excalibur0214** [comment]
> @Excalibur0214 did you think the VGG16 model is trained with image channels order BGR?

Yes, I did, but I don't think (104,117,123) is in BGR order, which is different from what the author thought. Maybe the author is right, but I'm not sure.

**Comment by Damon2019** [comment]
@Excalibur0214 hi, i  want to use resnet  instead of vgg，Can you give me some advice about how to modify the code ? Thank you very much and look forward to your reply.
