### ISSUE TITLE
请教下，我用新的训练集进行训练，一共10类，测试时候出现这个错误：

### ISSUE THREAD

**Issue by chenchch94** [ruinmessi/RFBNet#52]
RuntimeError: Error(s) in loading state_dict for RFBNet:
        size mismatch for conf.0.weight: copying a param of torch.Size([126, 512, 3, 3]) from checkpoint, where the shape is torch.Size([66, 512, 3, 3]) in current model.
        size mismatch for conf.0.bias: copying a param of torch.Size([126]) from checkpoint, where the shape is torch.Size([66]) in current model.
        size mismatch for conf.1.weight: copying a param of torch.Size([126, 1024, 3, 3]) from checkpoint, where the shape is torch.Size([66, 1024, 3, 3]) in current model.
        size mismatch for conf.1.bias: copying a param of torch.Size([126]) from checkpoint, where the shape is torch.Size([66]) in current model.
        size mismatch for conf.2.weight: copying a param of torch.Size([126, 512, 3, 3]) from checkpoint, where the shape is torch.Size([66, 512, 3, 3]) in current model.
        size mismatch for conf.2.bias: copying a param of torch.Size([126]) from checkpoint, where the shape is torch.Size([66]) in current model.
        size mismatch for conf.3.weight: copying a param of torch.Size([126, 256, 3, 3]) from checkpoint, where the shape is torch.Size([66, 256, 3, 3]) in current model.
        size mismatch for conf.3.bias: copying a param of torch.Size([126]) from checkpoint, where the shape is torch.Size([66]) in current model.
        size mismatch for conf.4.weight: copying a param of torch.Size([84, 256, 3, 3]) from checkpoint, where the shape is torch.Size([44, 256, 3, 3]) in current model.
        size mismatch for conf.4.bias: copying a param of torch.Size([84]) from checkpoint, where the shape is torch.Size([44]) in current model.
        size mismatch for conf.5.weight: copying a param of torch.Size([84, 256, 3, 3]) from checkpoint, where the shape is torch.Size([44, 256, 3, 3]) in current model.
        size mismatch for conf.5.bias: copying a param of torch.Size([84]) from checkpoint, where the shape is torch.Size([44]) in current model.

我并不清楚前面的checkpoint的torch.size的126/84这个是在哪修改的

**Comment by chenchch94** [comment]
已经解决了

**Comment by BestSongEver** [comment]
请问你在自己的10类数据集上成功训练了吗？@chenchch94
我在我的单类数据集上训练，AP=0。应该是代码没改对，可以告诉我你怎么改的吗？
非常感谢！

我改了 data/voc0712.py、models/*.py 、train_RFB.py和test_RFB.py 中的类别NUM_CLASSES及类别数目num_classes。
请问还需要怎么改？
谢谢！

**Comment by haochange** [comment]
> 
> 
> 请问你在自己的10类数据集上成功训练了吗？@chenchch94
> 我在我的单类数据集上训练，AP=0。应该是代码没改对，可以告诉我你怎么改的吗？
> 非常感谢！
> 
> 我改了 data/voc0712.py、models/*.py 、train_RFB.py和test_RFB.py 中的类别NUM_CLASSES及类别数目num_classes。
> 请问还需要怎么改？
> 谢谢！

do you solve the problem?

**Comment by chenchch94** [comment]
我跑了新数据集，没收敛。


发自网易邮箱大师
在2018年12月10日 11:30，million 写道：

请问你在自己的10类数据集上成功训练了吗？@chenchch94
我在我的单类数据集上训练，AP=0。应该是代码没改对，可以告诉我你怎么改的吗？
非常感谢！

我改了 data/voc0712.py、models/*.py 、train_RFB.py和test_RFB.py 中的类别NUM_CLASSES及类别数目num_classes。
请问还需要怎么改？
谢谢！

do you solve the problem?

**Comment by haochange** [comment]
> 
> 我跑了新数据集，没收敛。 发自网易邮箱大师 在2018年12月10日 11:30，million 写道： 请问你在自己的10类数据集上成功训练了吗？@chenchch94 我在我的单类数据集上训练，AP=0。应该是代码没改对，可以告诉我你怎么改的吗？ 非常感谢！ 我改了 data/voc0712.py、models/*.py 、train_RFB.py和test_RFB.py 中的类别NUM_CLASSES及类别数目num_classes。 请问还需要怎么改？ 谢谢！ do you solve the problem? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

I also met the problem.😭  The training set may be too hard to train.

**Comment by chenchch94** [comment]
Voc数据集可以收敛到0.803+




发自网易邮箱大师
在2018年12月11日 16:48，million 写道：

我跑了新数据集，没收敛。 发自网易邮箱大师 在2018年12月10日 11:30，million 写道： 请问你在自己的10类数据集上成功训练了吗？@chenchch94 我在我的单类数据集上训练，AP=0。应该是代码没改对，可以告诉我你怎么改的吗？ 非常感谢！ 我改了 data/voc0712.py、models/*.py 、train_RFB.py和test_RFB.py 中的类别NUM_CLASSES及类别数目num_classes。 请问还需要怎么改？ 谢谢！ do you solve the problem? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

I also met the problem.😭 The training set may be too hard to train.

**Comment by haochange** [comment]
loss_f + loss_c equals 0.803+ ?
loss_c  in my experments is about 1.x, loss_f is about 0.8. 
I tried many times, loss is very unusual.

**Comment by chenchch94** [comment]
The mAP of VOC2007




发自网易邮箱大师
在2018年12月12日 14:52，million 写道：

loss_f + loss_c equals 0.803+ ?
loss_c in my experments is about 1.x, loss_f is about 0.8.
I tried many times, loss is very unusual.

**Comment by Yann1ChOU** [comment]
> RuntimeError: Error(s) in loading state_dict for RFBNet:
> size mismatch for conf.0.weight: copying a param of torch.Size([126, 512, 3, 3]) from checkpoint, where the shape is torch.Size([66, 512, 3, 3]) in current model.
> size mismatch for conf.0.bias: copying a param of torch.Size([126]) from checkpoint, where the shape is torch.Size([66]) in current model.
> size mismatch for conf.1.weight: copying a param of torch.Size([126, 1024, 3, 3]) from checkpoint, where the shape is torch.Size([66, 1024, 3, 3]) in current model.
> size mismatch for conf.1.bias: copying a param of torch.Size([126]) from checkpoint, where the shape is torch.Size([66]) in current model.
> size mismatch for conf.2.weight: copying a param of torch.Size([126, 512, 3, 3]) from checkpoint, where the shape is torch.Size([66, 512, 3, 3]) in current model.
> size mismatch for conf.2.bias: copying a param of torch.Size([126]) from checkpoint, where the shape is torch.Size([66]) in current model.
> size mismatch for conf.3.weight: copying a param of torch.Size([126, 256, 3, 3]) from checkpoint, where the shape is torch.Size([66, 256, 3, 3]) in current model.
> size mismatch for conf.3.bias: copying a param of torch.Size([126]) from checkpoint, where the shape is torch.Size([66]) in current model.
> size mismatch for conf.4.weight: copying a param of torch.Size([84, 256, 3, 3]) from checkpoint, where the shape is torch.Size([44, 256, 3, 3]) in current model.
> size mismatch for conf.4.bias: copying a param of torch.Size([84]) from checkpoint, where the shape is torch.Size([44]) in current model.
> size mismatch for conf.5.weight: copying a param of torch.Size([84, 256, 3, 3]) from checkpoint, where the shape is torch.Size([44, 256, 3, 3]) in current model.
> size mismatch for conf.5.bias: copying a param of torch.Size([84]) from checkpoint, where the shape is torch.Size([44]) in current model.
> 
> 我并不清楚前面的checkpoint的torch.size的126/84这个是在哪修改的

请问是怎么修改的呢？

**Comment by haochange** [comment]
> 
> 
> > RuntimeError: Error(s) in loading state_dict for RFBNet:
> > size mismatch for conf.0.weight: copying a param of torch.Size([126, 512, 3, 3]) from checkpoint, where the shape is torch.Size([66, 512, 3, 3]) in current model.
> > size mismatch for conf.0.bias: copying a param of torch.Size([126]) from checkpoint, where the shape is torch.Size([66]) in current model.
> > size mismatch for conf.1.weight: copying a param of torch.Size([126, 1024, 3, 3]) from checkpoint, where the shape is torch.Size([66, 1024, 3, 3]) in current model.
> > size mismatch for conf.1.bias: copying a param of torch.Size([126]) from checkpoint, where the shape is torch.Size([66]) in current model.
> > size mismatch for conf.2.weight: copying a param of torch.Size([126, 512, 3, 3]) from checkpoint, where the shape is torch.Size([66, 512, 3, 3]) in current model.
> > size mismatch for conf.2.bias: copying a param of torch.Size([126]) from checkpoint, where the shape is torch.Size([66]) in current model.
> > size mismatch for conf.3.weight: copying a param of torch.Size([126, 256, 3, 3]) from checkpoint, where the shape is torch.Size([66, 256, 3, 3]) in current model.
> > size mismatch for conf.3.bias: copying a param of torch.Size([126]) from checkpoint, where the shape is torch.Size([66]) in current model.
> > size mismatch for conf.4.weight: copying a param of torch.Size([84, 256, 3, 3]) from checkpoint, where the shape is torch.Size([44, 256, 3, 3]) in current model.
> > size mismatch for conf.4.bias: copying a param of torch.Size([84]) from checkpoint, where the shape is torch.Size([44]) in current model.
> > size mismatch for conf.5.weight: copying a param of torch.Size([84, 256, 3, 3]) from checkpoint, where the shape is torch.Size([44, 256, 3, 3]) in current model.
> > size mismatch for conf.5.bias: copying a param of torch.Size([84]) from checkpoint, where the shape is torch.Size([44]) in current model.
> > 我并不清楚前面的checkpoint的torch.size的126/84这个是在哪修改的
> 
> 请问是怎么修改的呢？

could you solve it？ what about the performance？

**Comment by wyj18502986957** [comment]
> RuntimeError: Error(s) in loading state_dict for RFBNet:
> size mismatch for conf.0.weight: copying a param of torch.Size([126, 512, 3, 3]) from checkpoint, where the shape is torch.Size([66, 512, 3, 3]) in current model.
> size mismatch for conf.0.bias: copying a param of torch.Size([126]) from checkpoint, where the shape is torch.Size([66]) in current model.
> size mismatch for conf.1.weight: copying a param of torch.Size([126, 1024, 3, 3]) from checkpoint, where the shape is torch.Size([66, 1024, 3, 3]) in current model.
> size mismatch for conf.1.bias: copying a param of torch.Size([126]) from checkpoint, where the shape is torch.Size([66]) in current model.
> size mismatch for conf.2.weight: copying a param of torch.Size([126, 512, 3, 3]) from checkpoint, where the shape is torch.Size([66, 512, 3, 3]) in current model.
> size mismatch for conf.2.bias: copying a param of torch.Size([126]) from checkpoint, where the shape is torch.Size([66]) in current model.
> size mismatch for conf.3.weight: copying a param of torch.Size([126, 256, 3, 3]) from checkpoint, where the shape is torch.Size([66, 256, 3, 3]) in current model.
> size mismatch for conf.3.bias: copying a param of torch.Size([126]) from checkpoint, where the shape is torch.Size([66]) in current model.
> size mismatch for conf.4.weight: copying a param of torch.Size([84, 256, 3, 3]) from checkpoint, where the shape is torch.Size([44, 256, 3, 3]) in current model.
> size mismatch for conf.4.bias: copying a param of torch.Size([84]) from checkpoint, where the shape is torch.Size([44]) in current model.
> size mismatch for conf.5.weight: copying a param of torch.Size([84, 256, 3, 3]) from checkpoint, where the shape is torch.Size([44, 256, 3, 3]) in current model.
> size mismatch for conf.5.bias: copying a param of torch.Size([84]) from checkpoint, where the shape is torch.Size([44]) in current model.
> 
> 我并不清楚前面的checkpoint的torch.size的126/84这个是在哪修改的

@chenchch94 请问这个怎么改，看到联系我一下麻烦了 mail:1124204537@qq.com
