### ISSUE TITLE
Batch Test

### ISSUE THREAD

**Issue by wgqbit95** [ruinmessi/RFBNet#57]
Here, I have a little problem in testing. Cause I find the GPU occupation rate is really low during testing and the speed of testing is really slow.  Can I test a batch of images during testing?  Plz help me~ o(╥﹏╥)o

**Comment by ruinmessi** [comment]
@wgqbit95 The current code dose not support batch testing. If you wanna testing a batch in one single GPU, you may just modify the test_RFB.py to use a non-shuffle dataloader, and decode the detection results separately. For multi-GPU testing, I think you may need to design a new test engine and it is a non-trivial work.
