### ISSUE TITLE
求教代码中conv7_fc后面接了3个RFB模块？

### ISSUE THREAD

**Issue by 237014845** [ruinmessi/RFBNet#58]
您好，根据论文里面的图是conv7_fc后面直接连了俩个sride=2的RFB模块，然后conv7_fc再经过一个stride=1的RFB模块来预测和回归，但是代码里面是conv7_fc直接经过stride=1的RFB模块再经过俩个stride=2的RFB模块，然后把stride=1的RFB模块的输出直接引到预测和回归。请问是这样的吗？

**Comment by 237014845** [comment]
刚接触深度学习不久，麻烦您有空回答一下，小白不胜感激

**Comment by wgqbit95** [comment]
Maybe it is the same issue. https://github.com/ruinmessi/RFBNet/issues/27
