### ISSUE TITLE
hi  author,  can you show your loss information ? by several times training, my loss wanders between 0.3 - 0.8 all the time

### ISSUE THREAD

**Issue by neoSight001** [ruinmessi/RFBNet#60]

**Comment by ruinmessi** [comment]
@neoSight001  for classfication, the loss is around 2 for COCO and 1 for VOC, the bounding box loss is around 0.5.

**Comment by nuist-xinyu** [comment]
Epoch:1 || epochiter: 330/544|| Totel iter 330 || L: 2.8262 C: 3.1523||Batch time: 0.3125 sec. ||LR: 0.00048617
Epoch:1 || epochiter: 340/544|| Totel iter 340 || L: 3.5080 C: 2.8519||Batch time: 0.3134 sec. ||LR: 0.00050088
Traceback (most recent call last):
  File "train_RFB.py", line 261, in <module>
    train()
  File "train_RFB.py", line 212, in train
    images, targets = next(batch_iterator)
  File "/home/xinyu/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 322, in __next__
    return self._process_next_batch(batch)
  File "/home/xinyu/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
KeyError: 'Traceback (most recent call last):\n  File "/home/xinyu/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/xinyu/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/xinyu/RFBNet-master/data/voc0712.py", line 179, in __getitem__\n    target = self.target_transform(target)\n  File "/home/xinyu/RFBNet-master/data/voc0712.py", li


hi，do you know how to solve this problem？
