### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by transcendentsky** [ruinmessi/RFBNet#62]
Thanks for your work, could you please share your weights of RFB_300_coco ? i wanna check the result with mine (only 28.2 in minival2014 ) .  so what about the right result ?

**Comment by ruinmessi** [comment]
@transcendentsky  I have changed the structure on RFB_vgg according to #23 . The re-training RFB_300_coco get 30.3 in minival2014, and I have not submit it to get the results in test-dev. Here is the [weights](https://pan.baidu.com/s/1vL_oNwhj0ksK593nApqDLw). And I will update it on README.md
