### ISSUE TITLE
Question in config.py

### ISSUE THREAD

**Issue by zieitokk** [ruinmessi/RFBNet#68]
Hi,

I have a question in config.py. The min_sizes and max_sizes are different between VOC_512 and COCO_512. Since they have the same SSD structure, why there are inconsistent between two min and max sizes? 

Thank you very much!

**Comment by ruinmessi** [comment]
@zieitokk COCO dataset has more small instances. This inconsistent follows from the original SSD paper.

**Comment by zieitokk** [comment]
@ruinmessi  Thank you for your reply. However, when I checked the original paper, it just said that the S_min and S_max are 0.2 amd 0.9 respectively. And the author said 

> In practice, one can also design a distribution of default boxes to
best fit a specific dataset.

So, would you mind telling me where can I find resource that can help me with calculating these steps?

Thank you again!
