### ISSUE TITLE
BasicConv  set bn=True will get error

### ISSUE THREAD

**Issue by hust-kevin** [ruinmessi/RFBNet#69]
ValueError: Expected more than 1 value per channel when training, got input size [1, 256, 1, 1]

**Comment by ruinmessi** [comment]
@hust-kevin bn=True is the default setting, so check your modification of the models and the size of input images.

**Comment by hust-kevin** [comment]
I did not modify the code ,I just  test the rfb model in RFB_Net_vgg.py

`a=torch.randn(1,3,300,300)
rfb=build_net('train')
out=rfb(a)`

then will get the error

**Comment by ruinmessi** [comment]
@hust-kevin ....em...the batch_norm need at least batchsize >=2, so use a = (2,3,300,300)  or  rfb=rfb.eval()
