### ISSUE TITLE
compile make.sh error

### ISSUE THREAD

**Issue by vickersmith** [ruinmessi/RFBNet#70]
when i run the make.sh, i met the error,can anybody knows how to deal with it ?

nms/cpu_nms.c:4:20: fatal error: Python.h: No such file or directory
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by haochange** [comment]
I met the same error.

**Comment by vickersmith** [comment]
originally,i used the pure pip installaition(with virtualenv) and error occured. when i change anaconda installation with relevant virtual environment ,it works.

**Comment by haochange** [comment]
> 
> 
> originally,i used the pure pip installaition(with virtualenv) and error occured. when i change anaconda installation with relevant virtual environment ,it works.

thank you!
