### ISSUE TITLE
the confidence threshold of demo.py 

### ISSUE THREAD

**Issue by deeppower** [ruinmessi/RFBNet#75]
Thanks for your great work.
I refer to your test_RFB.py and write a demo.py.
The confidence threshold of  test_RFB.py is 0.01, and what is best value of confidence threshold in demo.py？

**Comment by hxf930620** [comment]
> 感谢您的杰出工作。
> 我引用你的test_RFB.py并编写demo.py. 
> test_RFB.py的置信度阈值为0.01，demo.py中置信度阈值的最佳值是多少？

can you share your demo.py ?thank you!

**Comment by cherishfive** [comment]
> 感谢您的杰出工作。
> 我引用你的test_RFB.py并编写demo.py. 
> test_RFB.py的置信度阈值为0.01，demo.py中置信度阈值的最佳值是多少？

Can you share your demo.py? Thank you very much！1655984679@qq.com

**Comment by Xiehuaiqi** [comment]
> Thanks for your great work.
> I refer to your test_RFB.py and write a demo.py.
> The confidence threshold of test_RFB.py is 0.01, and what is best value of confidence threshold in demo.py？

Can you share your demo.py? Thank you very much！353850260@qq.com

**Comment by nuist-xinyu** [comment]
Can you share your demo.py? 
Thank you very much！626673305@qq.com
