### ISSUE TITLE
What do the loc layer and conf layer do??

### ISSUE THREAD

**Issue by hahanigehaha233** [ruinmessi/RFBNet#79]
I am newer in DL, please tell me the detail.

**Comment by zieitokk** [comment]
> I am newer in DL, please tell me the detail.

The loc layer is the estimation of location layer, which outputs feature maps and its dim is 
`batch_size x dim x dim x number_of_prior_boxes_at_each_position *4` 
(4 means the x_min, y_min, x_max, y_max). The conf layer is the classification layer, which outputs the feature maps and its dim is 
`batch_size x dim x dim x number_of_prior_boxes_at_each_position * number_of_classes(including background)`

**Comment by zieitokk** [comment]
> @zieitokk So the loc layer and conf layer are the term of the SSD model, no the trick of coding or debugging?

Yes, they are included in the SSD model. Neither of them is the trick of coding or debugging.

**Comment by eng100200** [comment]
@hahanigehaha233 can i ask you question?
