### ISSUE TITLE
More detail about Table 3 in paper

### ISSUE THREAD

**Issue by xychen9459** [ruinmessi/RFBNet#8]
Hi, @ruinmessi .

Thanks for your brilliant work. I want to ask you something about results in Table 3. 

Table 3 shows "Performance comparison of different block architectures". The architecture of RFB block is similar to inception [34] module in GoogLeNet, so I can regard results between RFB and inception as comparison between different block architectures. But the rest architecture such as Deformable CNN [4] , Dilated Conv [3]  are not the same (or similar) as RFB (actually they are deeply embedded with CNN networks such as VGG and ResNet). I wonder whether results in Table 3 come from replacing components in RFB block or directly replacing the whole network by Deformable CNN [4] , Dilated Conv [3] and others. I have confused with these results for a long time and need some clearer detail on experiments.

Thanks.

**Comment by ruinmessi** [comment]
@xychen9459  In Table 3, I just replace the RFB block in Table 6 by Deformable CNN or Dilated conv layers, keeping the same stride as the origin. The channels of each layer may be different as controlling the total number of parameters.
