### ISSUE TITLE
Speed of RFBNet and SSD on COCO and VOC, have you consider the nms time?

### ISSUE THREAD

**Issue by tjulyz** [ruinmessi/RFBNet#92]
Hi,
Thank you for share your codes!
When I test your code on VOC and SSD, I cannot reproduce the speed as you reported. 
My configuration is Titan XP, pytorch 0.4, cuda 9.0, and get 20+ms for VOC, 30+ms for COCO, not like yours (80+fps, and 15ms for COCO).  When test the speed, I use conf_thresh 0.01, cpunms.  I have also tried pytorch 0.3, still cannot reproduce the speed. The time of nms for me is ~20ms for COCO, and ~10ms for VOC. So have you consider the NMS time when report the fps?
Any advice for getting the correct speed?
Thank you very much!

**Comment by ruinmessi** [comment]
@tjulyz  In my test, I get ~9ms inference speed plus ~3 ms CPU nms time with pytorch 0.3.1, cuda 9.0 on VOC 300. For COCO 300 the GPU nms time increase to ~6ms. These measurements all ignore the first 50 samples when the GPU is warming up. For your configuration, I guess the bottleneck mainly comes from the nms. You can try the gpu nms version or use a higher version of numpy and cython, or a more powerful cpu.

**Comment by tjulyz** [comment]
Great, thank you very much!

**Comment by vaesl** [comment]
I also met the same problem. My configuration is Titan XP, pytorch 0.3.1, cuda 9.0 and I am using the nms of gpu version. For COCO 300, the inference speed is ~6 ms/img while the nms time is ~12ms/img, which looks strange. Could you please provide some more suggestions? Many thanks!

**Comment by GGjerry01** [comment]
i alse met the same problem, gpu_nms also need cost much time than model infer. i am very worried about this

**Comment by dishen12** [comment]
@ruinmessi when i test on pytorch 0.3.1, cuda 9.0, i met the problem **Segmentation fault(Core Dump)**, do you konw where is problem lie?
