### ISSUE TITLE
test trained model RFBNet300

### ISSUE THREAD

**Issue by JingpengSun** [ruinmessi/RFBNet#97]
Hi, thank you for your great work.

When I try to evaluate the trained model RFBNet300_VOC_80_7, which is one of your given models. 
I got the following error:

im_detect: 1/10 0.022s 0.001s
Evaluating detections
Writing aeroplane VOC results file
Writing bicycle VOC results file
Writing bird VOC results file
Writing boat VOC results file
Writing bottle VOC results file
Writing bus VOC results file
Writing car VOC results file
Writing cat VOC results file
Writing chair VOC results file
Writing cow VOC results file
Writing diningtable VOC results file
Writing dog VOC results file
Writing horse VOC results file
Writing motorbike VOC results file
Writing person VOC results file
Writing pottedplant VOC results file
Writing sheep VOC results file
Writing sofa VOC results file
Writing train VOC results file
Writing tvmonitor VOC results file
VOC07 metric? Yes
Traceback (most recent call last):
  File "/home/johnsnore/Research/RFBNet/test_RFB.py", line 190, in <module>
    top_k, thresh=0.01)
  File "/home/johnsnore/Research/RFBNet/test_RFB.py", line 143, in test_net
    testset.evaluate_detections(all_boxes, save_folder)
  File "/home/johnsnore/Research/RFBNet/data/voc0712.py", line 253, in evaluate_detections
    self._do_python_eval(output_dir)
  File "/home/johnsnore/Research/RFBNet/data/voc0712.py", line 310, in _do_python_eval
    use_07_metric=use_07_metric)
  File "/home/johnsnore/Research/RFBNet/data/voc_eval.py", line 152, in voc_eval
    BB = BB[sorted_ind, :]
IndexError: too many indices for array

And I found BB=[]
Is that something wrong?
Should I do something else before run test_RFB.py？

**Comment by JingpengSun** [comment]
I figure it out. 
Thank you~
I close this.

**Comment by 0801130205** [comment]
@JingpengSun I only get a mAP of 0.8056 not 80.7% posted in github. And you?
`AP for aeroplane = 0.8503
AP for bicycle = 0.8607
AP for bird = 0.7765
AP for boat = 0.7568
AP for bottle = 0.6060
AP for bus = 0.8886
AP for car = 0.8758
AP for cat = 0.8679
AP for chair = 0.6422
AP for cow = 0.8527
AP for diningtable = 0.7793
AP for dog = 0.8610
AP for horse = 0.8899
AP for motorbike = 0.8706
AP for person = 0.8226
AP for pottedplant = 0.5870
AP for sheep = 0.8153
AP for sofa = 0.8113
AP for train = 0.8825
AP for tvmonitor = 0.8145
Mean AP = 0.8056
~~~~~~~~
Results:
0.850
0.861
0.777
0.757
0.606
0.889
0.876
0.868
0.642
0.853
0.779
0.861
0.890
0.871
0.823
0.587
0.815
0.811
0.882
0.815
0.806
~~~~~~~~
`

**Comment by darking-ou** [comment]
Hello! I also meet the problem. 

BB = BB[sorted_ind, :]
IndexError: too many indices for array

How to solve it? Thank you! @JingpengSun

**Comment by nuist-xinyu** [comment]
Epoch:1 || epochiter: 330/544|| Totel iter 330 || L: 2.8262 C: 3.1523||Batch time: 0.3125 sec. ||LR: 0.00048617
Epoch:1 || epochiter: 340/544|| Totel iter 340 || L: 3.5080 C: 2.8519||Batch time: 0.3134 sec. ||LR: 0.00050088
Traceback (most recent call last):
  File "train_RFB.py", line 261, in <module>
    train()
  File "train_RFB.py", line 212, in train
    images, targets = next(batch_iterator)
  File "/home/xinyu/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 322, in __next__
    return self._process_next_batch(batch)
  File "/home/xinyu/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
KeyError: 'Traceback (most recent call last):\n  File "/home/xinyu/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/xinyu/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/xinyu/RFBNet-master/data/voc0712.py", line 179, in __getitem__\n    target = self.target_transform(target)\n  File "/home/xinyu/RFBNet-master/data/voc0712.py", li


hi，do you know how to solve this problem？

**Comment by jiangjun001** [comment]
> I figure it out.
> Thank you~
> I close this.

I meet the same question with you,how to do with it?thank you

**Comment by Damon2019** [comment]
@JingpengSun i also meet the same question with you,how to do with it? thanks
